name: SmartInvs
version: 1.4.0
description: Inventory API for your Bukkit Plugins.
authors: [MinusKube, 'Partyhat.gg']
api-version: 1.20
website: https://github.com/partyhatgg/SmartInvs
main: dev.partyhat.inventory.SmartInvsPlugin