name: SmartInvs
version: 2.0.0
description: Inventory API for your Bukkit Plugins.
author: MCParty Team
api-version: 1.19.2
website: https://github.com/mcpartylive/SmartInvs
main: live.mcparty.inventory.SmartInvsPlugin