name: SmartInvs
version: 1.3.3
description: Inventory API for your Bukkit Plugins.
author: MinusKube
api-version: 1.18
website: https://github.com/MinusKube/SmartInvs
main: live.mcparty.inventory.SmartInvsPlugin